excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://duongphuhiep.github.io
title: DUONG Phu-Hiep
tagline: passionate programmer
description: Professional experiences and opinions
paginate: 5